apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd_playground
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: dev_app
    repoURL: https://github.com/MaoKo/argocd-achiu-au.git
    targetRevision: first_test
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
