apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-playground
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc 
  project: development
  source: 
    path: dev_app
    repoURL: https://github.com/MaoKo/argocd-achiu-au.git
    targetRevision: HEAD
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
