apiVersion: v1
kind: Service
metadata:
  labels:
    app: playground
  name: playground
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: playground
